AWSTemplateFormatVersion: "2010-09-09"
Description: Create new CloudFront Distribution

Parameters:
  S3BucketNameCDN:
    Description: "S3 Bucket name for CloudFront distribution static contents"
    Type: String
  HostZoneId:
    Description: "Route53 hosted zone id (Z0xxx)"
    Type: String
  ACMCertificateCF:
    Description: "ACM Certificate ARN in us-east-1 for CloudFront"
    Type: String
  DomainNameCF:
    Description: "domain name for CloudFront"
    Type: String

Resources:
###############################################################################
# S3 Bucket
###############################################################################
  # TastylogS3BucketCDN:
  #   Type: AWS::S3::Bucket
  #   Properties:
  #     BucketName: !Sub "${S3BucketNameCDN}"
  #     PublicAccessBlockConfiguration:
  #       BlockPublicAcls: "true"
  #       BlockPublicPolicy: "true"
  #       IgnorePublicAcls: "true"
  #       RestrictPublicBuckets: "true"

  TastylogS3BucketPolicyCDN:
    Type: AWS::S3::BucketPolicy
    Properties:
      # Bucket: !Ref "TastylogS3BucketCDN"
      Bucket: !Sub "${S3BucketNameCDN}" # use S3 bucket created outside the CloudFront
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Action:
              - "s3:GetObject"
            Effect: "Allow"
            # Resource: !Sub "${TastylogS3BucketCDN.Arn}/*"
            Resource: !Sub "arn:aws:s3:::${S3BucketNameCDN}/*"
            Principal:
              CanonicalUser: !GetAtt "TastylogOAI.S3CanonicalUserId"

###############################################################################
# CloudFront OAI
###############################################################################
  TastylogOAI:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: "CloudFront OAI for Static Web Site"

###############################################################################
# CloudFront Distribution
###############################################################################
  TastylogCloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        #--------------------------------
        # Basic
        #--------------------------------
        Enabled: "true"
        DefaultRootObject: ""
        #--------------------------------
        # Origin
        #--------------------------------
        Origins:
          #--------------------------------
          # Dynamic Contents: ALB
          #--------------------------------
          - DomainName: !ImportValue "TastylogALB-ALBDomainName"
            # A unique identifier for the origin. This value must be unique within the distribution.
            # Use this value to specify the TargetOriginId in a CacheBehavior or DefaultCacheBehavior.
            Id: "Dynamic-ALB"
            CustomOriginConfig:
              OriginProtocolPolicy: "https-only" # http-only | https-only | match-viewer
              # HTTPPort: "80"
              HTTPSPort: "443"
              # the minimum SSL/TLS protocol that CloudFront uses when connecting to your origin over HTTPS
              # SSLv3, TLSv1, TLSv1.1, and TLSv1.2
              OriginSSLProtocols: 
                - "TLSv1"
                - "TLSv1.1"
                - "TLSv1.2"
              # Specifies how long, in seconds, CloudFront persists its connection to the origin.
              OriginKeepaliveTimeout: "5" # 1-60 default 5
              # Specifies how long, in seconds, CloudFront waits for a response from the origin. 
              OriginReadTimeout: "30" # 1-60 default 30
          #--------------------------------
          # Static Contents: S3
          #--------------------------------
          # explicitly set the Region name to avoid StatusCode 307
          # https://aws.amazon.com/jp/premiumsupport/knowledge-center/s3-http-307-response/
          # - DomainName: !Join ["", [!Ref TastylogS3BucketCDN, !Sub ".s3-${AWS::Region}.amazonaws.com"]]
          - DomainName: !Sub "${S3BucketNameCDN}.s3-${AWS::Region}.amazonaws.com"
            # A unique identifier for the origin. This value must be unique within the distribution.
            # Use this value to specify the TargetOriginId in a CacheBehavior or DefaultCacheBehavior.
            Id: "WebStatic-S3"
            S3OriginConfig:
              OriginAccessIdentity:
                !Join ["", ["origin-access-identity/cloudfront/", !Ref "TastylogOAI"]]
        #--------------------------------
        # Cache Behavior (Default: dynamic contents)
        #--------------------------------
        DefaultCacheBehavior:
          TargetOriginId: "Dynamic-ALB"
          Compress: "true"
          ViewerProtocolPolicy: "redirect-to-https" # allow-all | redirect-to-https | https-only
          AllowedMethods:
            - "GET"
            - "HEAD"
          CachePolicyId: "4135ea2d-6df8-44a3-9df3-4b5a84be39ad" # CachingDisabled (managed)
          OriginRequestPolicyId: "216adef6-5c7f-47e4-b989-5492eafa07d3" # AllViewer (managed)
        CacheBehaviors:
          #--------------------------------
          # Cache Behavior (Static Contents: S3)
          #--------------------------------
          - PathPattern: "/public/*"
            TargetOriginId: "WebStatic-S3"
            Compress: "true"
            ViewerProtocolPolicy: "redirect-to-https" # allow-all | redirect-to-https | https-only
            AllowedMethods:
              - "GET"
              - "HEAD"
            CachePolicyId: "658327ea-f89d-4fab-a63d-7e88639e58f6" # CachingOptimized (managed; recommended for s3 origin)
            OriginRequestPolicyId: "88a5eaf4-2fd4-4709-b370-b4c650ea3fcf" # CORS-S3Origin (managed)
        #--------------------------------
        # Viewer
        #--------------------------------
        Aliases:
          - !Sub "${DomainNameCF}"
        ViewerCertificate:
          AcmCertificateArn: !Sub "${ACMCertificateCF}"
          MinimumProtocolVersion: "TLSv1.2_2021" # AWS recommends
          SslSupportMethod: "sni-only"
        #--------------------------------
        # Setting Additional
        #--------------------------------
        PriceClass: "PriceClass_All" # use all CloudFront edge locations
        # Logging:
        #   Bucket: !GetAtt S3BucketLogs.DomainName
        #   IncludeCookies: false
        #   Prefix: 'cdn/'
        HttpVersion: "http2"
        IPV6Enabled: "true"

###############################################################################
# Route53 RecordSet
###############################################################################
  DnsRecordALB:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Sub "${HostZoneId}"
      Comment: "DNS for CF"
      Name: !Sub "${DomainNameCF}"
      Type: "A"
      AliasTarget:
        # Specify Z2FDTNDATAQYW2. 
        # This is always the hosted zone ID when you create an alias record 
        # that routes traffic to a CloudFront distribution.
        HostedZoneId: "Z2FDTNDATAQYW2"
        DNSName: !GetAtt "TastylogCloudFrontDistribution.DomainName"
